### ISSUE TITLE
add richer Discord interactions

### ISSUE THREAD

**Issue by wazam** [wazam/discord-sports-notification#20]
[Application/Slash Commands](https://discord.com/developers/docs/interactions/application-commands)
- view/change ENVs
- view daily games & scores
- fetch stream link(s)
- remind me of upcoming games

**Comment by noahschechter** [comment]
I would think about ENV vars as "initial" values for configuration settings

for example: 
export MLB_INNING_THRESHOLD=8

That would set the initial value for the "MLB_INNING_THRESHOLD" configuration setting when the application is loaded in memory at runtime

Afterwards, once the application is running, we would be changing the configuration settings through program logic, not through ENV vars. Changing it thru program logic will modify the specific piece of memory that holds the  "MLB_INNING_THRESHOLD" value, so the program knows the next time it tries to read that value
