### ISSUE TITLE
Add support for MLB games

### ISSUE THREAD

**Issue by wazam** [wazam/discord-sports-notification#8]
Possible starting points:
[toddrob99/MLB-StatsAPI](https://github.com/toddrob99/MLB-StatsAPI)
[brianhaferkamp/mlbapidata](https://github.com/brianhaferkamp/mlbapidata)
[appac/mlb-data-api-docs](https://github.com/appac/mlb-data-api-docs)

**Comment by wazam** [comment]
http://statsapi.mlb.com/api/v1.1/game/706918/feed/live

liveData.plays.currentPlay.matchup.splits.menOnBase = "RISP||Men_On||Empty"

liveData.plays.currentPlay.matchup.postOnFirst.id > 0
liveData.plays.currentPlay.matchup.postOnSecond.id > 0
liveData.plays.currentPlay.matchup.postOnThird.id > 0

**Comment by noahschechter** [comment]
http://statsapi.mlb.com/api/v1.1/game/706918/feed/live[
["liveData"]["currentPlay"]["about"] - inning
["liveData"]["currentPlay"]["about"] - scores

["liveData"]["currentPlay"]["matchup"]["splits"]["menOnBase"] == "RISP"

**Comment by wazam** [comment]
http://statsapi.mlb.com/api/v1/schedule/games/?sportId=1
dates.0.games.[#].teams.away.leagueRecord.score
dates.0.games.[#].teams.home.leagueRecord.score

**Comment by wazam** [comment]
WIP #15
